name: Cypress test
description: Creating test action.
author: xdigu

inputs:
  base_url:
    description: "base url"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress run with env
      uses: cypress-io/github-action@v6
      with:
        env: BASE_URL=${{ inputs.base_url }}
        project: ${{ GITHUB_ACTION_PATH }}
      env:
        BASE_URL: ${{ inputs.base_url }}

branding:
  icon: terminal
  color: red
