name: deployment CI

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: ${{ steps.shell.outputs.url }}

    steps:
      - name: sh
        id: shell
        run: |
          echo "url=https://www.google.com" >> $GITHUB_OUTPUT
