name: Hello world

on:
  pull_request:
    branches: ["develop"]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        uses: xdigu/cypress-test@main
        with:
          base_url: "https://google.com"
          environment: "test"
