name: validate pull request

on:
  pull_request:
    branches: ["develop"]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Get deployment URL
        id: get-deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        env:
          BASE_URL: ${{ steps.get-deployment.outputs.deployment }}
