name: action with matrix

on:
  pull_request:
    branches: ["develop"]

jobs:
  cypress-validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 1
          - 2
          - 3
        device:
          - desktop
          - mobile

    steps:
      - name: Get deployment URL
        id: get-deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress run
        uses: xdigu/cypress-test@main
        with:
          base_url: ${{ steps.get-deployment.outputs.deployment }}
